language: python
sudo: required
dist: trusty
git:
  depth: 5
matrix:
  include:
  - python: 2.7
  - python: 3.5
  - python: 3.6
before_install:
- travis/install_pandoc.sh
script:
- python setup.py sdist
- pip install dist/`ls dist | grep -i -E '\.(gz)$' | head -1`
- pushd /
- python -c "import sys; import limix_exp; sys.exit(limix_exp.test())"
- popd
notifications:
  email: false
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: gAoldcJqRpgRdK4a3N35OkYAr8zLRcH0ucH1CfYa2RYmjwOx4NRAq2rbnZJOyoSb+1vPTuDUlve/5Aej8KFt99o+eWAktJKgUeOi54uRvfwT4M/0Awem9CP+PWt187i6fcs2rolatEhr5BcP8yW6/6h2Bg+iwmLpr4oeWg9bTgQW16AmOAiQ72TwjMMoxbLa3sPMxGbzZyX5GbXPQWBjwW5UTmekxRWD+hoLW5/r3/ZbsQ5UGBxcleRjYZxJM0XKoTs4iAGQQk6TCW5bwr8rPbg9XfBv+FgoRH/QEeFPBNDm+sUFiDK0kHIcQtPumwq+jLzCzY3CrEyZMFwLevpOrOhpHLdA8OV3+PZ9HXPVaGqDO3NYuVnsOrIH/cWjuU+27QPaJL92NcGI4liiHnBvNsXlFj0BTfBzKGd8NjSuSJ8JK5dBcciKHNQKirZx1iT9eQ8xliHO5jEAqZ7hjNn0D9hG3eQKlpyeJXOcQeHyAU5P9bR4c9GAWkJ4tEEidquTJxhBHIh8OusYqiCFklmNN12Ls0PWBDPrG5L08u62ocXQ086xFzgUoCU7HAXQUEgQeuGOvdOntm93ELQWMAylrc8nAYx61nn2GwRP/nK/bz+qJ7w9gIer1lFuc1w9gqgOg8GAIyEikQeLAM/W9vcjxSTnWfiGcZrAj92PymtzlV4=
  on:
    distributions: sdist bdist_wheel
    repo: Horta/limix-exp
